### ISSUE TITLE
AttributeError: type object 'Task' has no attribute '_Task__step'

### ISSUE THREAD

**Issue by emersonxsu** [erdewit/nest_asyncio#14]
When I try to call `nest_asyncio.apply()`

**Comment by erdewit** [comment]
Not sure what loop you're using but it can't really be one from asyncio. Only loops from asyncio can be patched.

**Comment by stroxler** [comment]
@erdewit I just hit the same issue

I think the cause may be that the asyncio maintainers have been messing with their internal api - for example, what used to be called `Task._Task__step` seems to have been renamed first to `Task._step` and then again to `Task.__step`.

My company's python3.6 kernel works fine with `nest_asyncio`, but our 3.7 is currently on the release where the method is named `Task._step`

Here's an example, this is the diff where `Task._step` was renamed to `Task.__step`:
https://github.com/python/cpython/commit/22feeb88b473b288950cdb2f6c5d28692274b5f9

I suppose we could probably modify `nest_asyncio` to discover the right function names on-the-fly, although the resulting code seems likely to get confusing :/
